### ISSUE TITLE
Question: will this approach improve performance?

### ISSUE THREAD

**Issue by havenchyk** [simpulton/angular-dynamic-templates#4]
Hi @simpulton!

I'm looking at your solution and wondering, will your approach be more performant then `ng-switch` inside the parent directive? Do you have any tests for it?

Thanks,
Uladzimir

**Comment by simpulton** [comment]
This approach is significantly more performant as the potential variations increase. For instance, what if you needed to accommodate 50+ potential variations in your layout? That would be near impossible to maintain using `ng-switch`. The watchers needed to maintain state in the DOM would be crippling after awhile. Using `$compile`, you only need to compile the layout once and it is done. I recommend checking out the talk that Scott Moss gave on watchers at ngConf 2015. It is excellent and plays heavily into this technique.

**Comment by havenchyk** [comment]
Thank you so much, Lukas, I'll check the video. After reading the docs of $compile and even after reading the sources it's not clear for me :)

**Comment by havenchyk** [comment]
Great video, thanks!
